/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AvaliacaoFilme__factory } from "./AvaliacaoFilme__factory";
export { Lock__factory } from "./Lock__factory";
